//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ewms.common.models.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=eWMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ALUMNO> TBL_ALUMNO { get; set; }
        public virtual DbSet<TBL_ALUMNO_GRADO> TBL_ALUMNO_GRADO { get; set; }
        public virtual DbSet<TBL_GRADO> TBL_GRADO { get; set; }
        public virtual DbSet<TBL_PROFESOR> TBL_PROFESOR { get; set; }
    }
}
