//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ewms.common.models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ALUMNO_GRADO
    {
        public int ID { get; set; }
        public Nullable<int> ALUMNO_ID { get; set; }
        public Nullable<int> GRADO_ID { get; set; }
        public string SECCION { get; set; }
    
        public virtual TBL_ALUMNO TBL_ALUMNO { get; set; }
        public virtual TBL_GRADO TBL_GRADO { get; set; }
    }
}
