//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ewms.common.models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ALUMNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_ALUMNO()
        {
            this.TBL_ALUMNO_GRADO = new HashSet<TBL_ALUMNO_GRADO>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string GENERO { get; set; }
        public string F_NACIMIENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ALUMNO_GRADO> TBL_ALUMNO_GRADO { get; set; }
    }
}
